### PR TITLE
Migrated BetterNether's PR BetterNether/pull/437 into BCLib

### LINKED ISSUE #43: Isolate BetterNether's crash fix into BCLib or a seperate mod.
I am creating this issue here and not on BetterEnd's repo because it affects both of your dimension mods.

I was doing another pregeneration test for BetterEnd's issue [#345](https://github.com/paulevsGitch/BetterEnd/issues/345) but as I only tested with Better End and BCLib, the previously solved crash on the nether generation happened again on the end dimension.
 
I think that BetterNether's fix of [#403](https://github.com/paulevsGitch/BetterNether/issues/403) from [my PR](https://github.com/paulevsGitch/BetterNether/pull/437) should be isolated into BCLib or a into a separate mod to avoid BetterEnd's dependency on BetterNether to avoid the crash. Alternatively the fix could also be replicated into BetterEnd as well, but I'm guessing your mods are not the cause of the issue but vanilla itself. 

End dimension crash log: (ignore the java.lang.ClassCastException errors from BetterEnd, that's already being discussed on [#345](https://github.com/paulevsGitch/BetterEnd/issues/345))
https://pastebin.com/ednmjFPt

### PR DESCRIPTION
**Pull request by davidalb97**
Moved BetterNether's PR [#437](https://github.com/paulevsGitch/BetterNether/pull/437) to BCLib, closes #43.

### CODE REVIEW

**Comment by paulevsGitch** [comment]
Why this mixin was inserted directly into the center of mixin list?

**Comment by davidalb97** [comment]
> Why this mixin was inserted directly into the center of mixin list?

Sorry, no reason, want me to place it somewhere else?

**Comment by paulevsGitch** [comment]
I will probably move it myself later

**Comment by paulevsGitch** [comment]
There are some style issues, like spaces instead of tabs, will be fixed too

**Pull request merged**
